### ISSUE TITLE
[Compose] Parser exited with code 1 Error

### ISSUE THREAD

**Issue by vagabond95** [figma/code-connect#346]
- Code Connect CLI version : 1.3.12
- code-connect-lib : 1.1.3
- com.figma.code.connect: 1.2.6
  - 1.2.7 version occurs "Could not find FigmaCodeConnect:annotations:unspecified" Error
- kotlin : 2.2.21

Full stacktrace
```
Trace: Error: Parser exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@figma/code-connect/dist/connect/parser_executables.js:119:32)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at getCodeConnectObjects (/usr/local/lib/node_modules/@figma/code-connect/dist/commands/connect.js:182:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getUnconnectedComponentsAndConnectedComponentMappings (/usr/local/lib/node_modules/@figma/code-connect/dist/connect/wizard/run_wizard.js:536:32)
```

--- 

I read in a previous issues(https://github.com/figma/code-connect/issues/272, https://github.com/figma/code-connect/issues/287)  that upgrading the Kotlin version to 2.2.x would resolve this problem. 
However, the issue still occurs in version 2.2.21. Could you please identify the root cause and suggest a solution?

**Comment by abbas-ali-fox** [comment]
+1.

**Comment by houssein-bee** [comment]
Same issue but with with those versions (same as the [official documentation](https://developers.figma.com/docs/code-connect/quickstart-guide/)): 
- kotlin = "2.2.10"
- code-connect-plugin = "1.2.7"
- code-connect-lib = "1.1.3"

stacktrace:
```
A problem occurred configuring project ':app:code-connect'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find FigmaCodeConnect:annotations:unspecified.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/FigmaCodeConnect/annotations/unspecified/annotations-unspecified.pom
       - https://dl.google.com/dl/android/maven2/FigmaCodeConnect/annotations/unspecified/annotations-unspecified.pom
       - https://repo.maven.apache.org/maven2/FigmaCodeConnect/annotations/unspecified/annotations-unspecified.pom
     Required by:
         buildscript of project ':app:code-connect' > com.figma.code.connect:com.figma.code.connect.gradle.plugin:1.2.7 > com.figma.code.connect:plugin:1.2.7

```

**Comment by vagabond95** [comment]
@houssein-bee 
This refers to the issue I mentioned earlier regarding the `Could not find FigmaCodeConnect:annotations:unspecified`

It seems likely that some dependencies are not being properly managed in the latest version.

**Comment by tweightman-figma** [comment]
Hi @vagabond95. Thanks for the report. I'm just trying to understand fully. Are you saying `Could not find FigmaCodeConnect:annotations:unspecified` only happens in 1.2.7, but on 1.2.6 you get `Parser exited with code 1` instead? In other words, two different errors on two different versions?

**Comment by vagabond95** [comment]
@tweightman-figma 

Both versions produce a Parser exited with code 1 error.

To summarize the workflow I did:
I tried the latest version, 1.2.7 -> com.figma.code.connect itself failed to load properly and occurred a `Parser exited with code 1 error`.

I thought this was a problem only with the latest version, so I downgraded to 1.2.6, but the same Parser error occurred.

**Comment by tweightman-figma** [comment]
@vagabond95 I've published 1.2.8 to Maven, can you see if that fixes this and let us know? Thanks!

https://plugins.gradle.org/plugin/com.figma.code.connect

**Comment by abbas-ali-fox** [comment]
> I'm just trying to understand fully. Are you saying Could not find FigmaCodeConnect:annotations:unspecified only happens in 1.2.7

Yes.

> on 1.2.6 you get Parser exited with code 1 instead?

I think @vagabond95 encountered that issue because of incompatible Kotlin version. If there was a compatibility map (for all or at least recent releases) in the docs that would be great because currently the documentation only mentions which version of Kotlin the latest code connect version supports.

@tweightman-figma I've tested the latest version `1.2.8` with Kotlin `2.2.10` and I can sync gradle and publish mappings without any issue. Thanks for the quick fix.

**Comment by vagabond95** [comment]
Not works for me 😭

- gradle sync issue -> ok, clearly fixed
- parser issue -> not fixed, same error logs

```
Trace: Error: Parser exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@figma/code-connect/dist/connect/parser_executables.js:119:32)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at getCodeConnectObjects (/usr/local/lib/node_modules/@figma/code-connect/dist/commands/connect.js:182:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getUnconnectedComponentsAndConnectedComponentMappings (/usr/local/lib/node_modules/@figma/code-connect/dist/connect/wizard/run_wizard.js:536:32)
    at async runWizard (/usr/local/lib/node_modules/@figma/code-connect/dist/connect/wizard/run_wizard.js:785:68)
Error calling parser: Error: Parser exited with code 1.
```
When this log occurs, what causes it and what should I fix?

--- 
## versions
- kotlin : 2.2.10
- code-connect-lib : 1.1.3
- com.figma.code.connect: 1.2.8

**Comment by tweightman-figma** [comment]
Good to hear the gradle problems are solved. That last error is likely the compiler failing. So it could be a kotlin/java setup problem, or is could be a syntax problem or similar in your template code. I'd double check all the syntax, and that you have the correct Code Connect annotations.

**Comment by vagabond95** [comment]
I would like to clarify if I have missed any crucial steps.

Steps I did:

1. Configured dependencies.

2. Executed figma connect CLI `figma connect`

3. Received the prompt: “Select the pages with the Figma components you'd like to map.” -> Selected the design system page. 

4.  Parser error occurred.

---

And questions are as follows:

1. What does "mapping" mean in the step “Select the pages with the Figma components you'd like to map”? Does this step mean the CLI is generating the necessary files for mapping, separate from the [this file](https://developers.figma.com/docs/code-connect/compose/)?

2. At what step in the overall process should I create a component using "Figma Annotations"? Do I need to prepare a file with Figma annotations mapped before running the Figma Connect CLI?
- Even after preparing components with Figma Annotation  and running figma connect, the parser error occurs too.
```kotlin

@FigmaConnect(url = "https://www.figma.com/design/XXX")
class Navigation1IcDoc {

    @FigmaChildren("Title")
    val centerText: String = "Title"

    @Composable
    fun Navigation1IcExample() {
        Navigation1Ic(
            centerText = centerText,
            startIconRes = R.drawable.ic_24_back
        )
    }
}
```

3. You told me to check for syntax errors, but could a parser error occur even if there's a problem with figma.config.json?

I configured it as follows.
```json
{
  "codeConnect": {
    "include": ["design/src/main/java/me/xxx/component/**/*.kt"],
    "exclude": [
      "**/test/**",
      "**/androidTest/**",
      "**/build/**",
      "**/*Test.kt",
      "**/*Preview.kt"
    ],
    "interactiveSetupFigmaFileUrl": "https://www.figma.com/design/XXX",
    "parser": "compose"
  }
}
```
The config file is located at the top level of the project and is written with a relative path according to the guide.

4. The documentation for Compose configuration seems fragmented, making it difficult to understand the exact integration steps. could you guide specific steps?

**Comment by vagabond95** [comment]
@tweightman-figma I found that it was caused by a gradle/java version compatibility issue.
thanks for support
