### ISSUE TITLE
"unpublish" is not working

### ISSUE THREAD

**Issue by 0xa3k5** [figma/code-connect#59]
hi, 

when I run `npmx figma connect unpublish` 

```
Unpublishing Code Connect files from Figma...
Successfully deleted:
-> https://www.figma.com/design/...&m=dev (Storybook)
-> https://www.figma.com/design/...&m=dev (Storybook)
-> https://www.figma.com/design/... (Storybook)
```

however, when I go to the dev mode to check, I can still see the generated Code Connect code block there. This is making it really hard to test and update props and configurations.

_happy to share more information regarding our reporsitory/team files if needed_

**Comment by rrabherufigma** [comment]
Hi @0xa3k5 , Please can you contact support via https://help.figma.com/hc/en-us/requests/new?ticket_form_id=360001744374 with more information on the files and code.

**Comment by glomotion** [comment]
i'm also seeing this issue. :(

**Comment by 0xa3k5** [comment]
i believe this is fixed now

**Comment by livvy-lee** [comment]
It says "Unpublishing Code Connect files from Figma... Successfully deleted:" but unpublish still doesn't seem to work.

**Comment by darshkpatel** [comment]
Connecting using the code connect cli, publishing a new version and unpublishing using the cli helped. Terrible UX :/

**Comment by joel-krueger** [comment]
I'm suffering this same issue, except I can't still view the code block. I'm unsure how it got into the state, but the Code Component in Library > Connect Components to Code > 'Select broken component' displays:
Error loading Code Connect
Failed to load Code Connect example

The console log shows:

<img width="852" height="350" alt="Image" src="https://github.com/user-attachments/assets/e83b18d4-9f4c-4fa0-b479-677074991c80" />

The MCP server tool call get_code_connect_map returns:
{
    "content": [
        {
            "type": "text",
            "text": "{\"61816:3761\":{\"source\":\"\",\"snippet\":\"{/* Code Connect Snippet Error */}\",\"snippetImports\":[],\"snippetNestedFunctions\":[],\"version\":\"figmadoc\",\"label\":\"React\"},\"61816:3765\":{\"source\":\"\",\"snippet\":\"{/* Code Connect Snippet Error */}\",\"snippetImports\":[],\"snippetNestedFunctions\":[],\"version\":\"figmadoc\",\"label\":\"React\"},\"61816:3769\":{\"source\":\"\",\"snippet\":\"{/* Code Connect Snippet Error */}\",\"snippetImports\":[],\"snippetNestedFunctions\":[],\"version\":\"figmadoc\",\"label\":\"React\"},\"61816:3773\":{\"source\":\"\",\"snippet\":\"{/* Code Connect Snippet Error */}\",\"snippetImports\":[],\"snippetNestedFunctions\":[],\"version\":\"figmadoc\",\"label\":\"React\"},\"61816:3778\":{\"source\":\"\",\"snippet\":\"{/* Code Connect Snippet Error */}\",\"snippetImports\":[],\"snippetNestedFunctions\":[],\"version\":\"figmadoc\",\"label\":\"React\"}}"
        }
    ]
}

The tool call get_design_context just hangs, never returning. But the console displays the 'Code Connect template: execution result is missing data' again.

Republishing seems to succeed but it stays in this state.
Unpublishing seems to succeed when done with all components, but it still remains in the error state.
Unpublishing specifying a node url and label returns 'No Code Connect CLI mapping found for this component'

**Comment by joel-krueger** [comment]
I just discovered the Error for viewing the code connect block is only on the figma desktop app. The web application displays fine.

Still unable to unpublish, though.
